# Generated by Django 6.0.3 on 2026-03-14 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_force_password_change'),
    ]

    operations = [
    ]
