# Generated by Django 6.0.3 on 2026-03-14 11:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('total_transactions', models.PositiveIntegerField(default=0)),
                ('total_collected', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_fees', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('expected_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('discrepancy', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('teller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['teller', 'date'], name='shifts_shif_teller__af7d76_idx'), models.Index(fields=['status'], name='shifts_shif_status_8c03df_idx')],
            },
        ),
    ]
