# Generated by Django 6.0.3 on 2026-03-14 02:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('voided', 'Voided'), ('pending_void', 'Pending Void Approval')], default='completed', max_length=20)),
                ('biller_name', models.CharField(max_length=200)),
                ('biller_account_number', models.CharField(max_length=50)),
                ('leyeco_reference', models.CharField(blank=True, max_length=100, verbose_name='LEYECO Reference No.')),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bill Amount (₱)')),
                ('service_fee', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=6)),
                ('total_due', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('cash_received', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cash Received (₱)')),
                ('change_given', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('void_reason', models.TextField(blank=True)),
                ('void_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('teller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('void_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='void_approvals', to=settings.AUTH_USER_MODEL)),
                ('void_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='void_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashDenomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.IntegerField(choices=[(1000, '₱1,000'), (500, '₱500'), (200, '₱200'), (100, '₱100'), (50, '₱50'), (20, '₱20'), (10, '₱10'), (5, '₱5'), (1, '₱1')])),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominations', to='transactions.payment')),
            ],
            options={
                'ordering': ['-denomination'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='transaction_created_e1a7ef_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['teller', 'created_at'], name='transaction_teller__78c192_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='transaction_status_5241e4_idx'),
        ),
    ]
