# Generated by Django 6.0.3 on 2026-03-14 03:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EODReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('total_transactions', models.PositiveIntegerField(default=0)),
                ('total_bill_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_service_fees', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('total_collected', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_change_given', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('declared_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('discrepancy', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eod_closures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EOD Reconciliation',
                'verbose_name_plural': 'EOD Reconciliations',
                'ordering': ['-date'],
            },
        ),
    ]
