# Generated by Django 6.0.3 on 2026-03-14 11:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='LEYECO Payment Center', max_length=200)),
                ('branch_address', models.CharField(blank=True, default='', max_length=300)),
                ('receipt_footer', models.CharField(blank=True, default='Thank you for using our payment service.', max_length=200)),
                ('service_fee', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=8)),
                ('email_enabled', models.BooleanField(default=False)),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=200)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_username', models.CharField(blank=True, max_length=200)),
                ('smtp_password', models.CharField(blank=True, max_length=200)),
                ('email_from', models.CharField(blank=True, help_text='Display name + address e.g. LEYECO Monitor <you@gmail.com>', max_length=200)),
                ('admin_email', models.CharField(blank=True, help_text='Comma-separated list of admin emails to notify', max_length=500)),
                ('notify_void_request', models.BooleanField(default=True, verbose_name='Email on void request')),
                ('notify_eod_shortage', models.BooleanField(default=True, verbose_name='Email on EOD shortage')),
                ('notify_daily_summary', models.BooleanField(default=True, verbose_name='Send daily summary email at EOD')),
                ('notify_new_user', models.BooleanField(default=False, verbose_name='Welcome email to new users')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
            },
        ),
    ]
